"""Render docs/data/audit_report.md from the saved manifests. Numbers are never typed by hand."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _table(header: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def _dist_rows(dists: dict[str, dict[str, Any]]) -> list[list[Any]]:
    keys = ["count", "mean", "p0", "p5", "p25", "p50", "p75", "p95", "p100"]
    return [[name] + [d.get(k, "") for k in keys] for name, d in dists.items()]


def render_audit_report(manifests_dir: Path) -> str:
    audit = _load(manifests_dir / "audit.json")
    leak = _load(manifests_dir / "leakage_report.json")
    meta = _load(manifests_dir / "split_manifest.meta.json")
    corpus = _load(manifests_dir / "corpus_manifest.json")
    raw = audit["raw"]
    exc = audit["exclusions"]
    cor = audit["corpus"]
    grp = audit["grouping"]
    dist_header = ["field", "count", "mean", "p0", "p5", "p25", "p50", "p75", "p95", "p100"]

    parts = [
        "# MedQuAD data audit report",
        "",
        "> Generated by `python -m medquad_qa.data report` from `data/manifests/{audit,leakage_report,"
        "split_manifest.meta,corpus_manifest}.json`. Do not edit by hand; rebuild and re-render instead.",
        "",
        f"- corpus_version: `{audit['corpus_version']}`",
        f"- split_version: `{audit['split_version']}`",
        f"- source sha256: `{audit['source_sha256']}`",
        f"- pipeline_version: `{corpus['pipeline_version']}`, contracts_version: `{corpus['contracts_version']}`",
        "",
        "## 1. Raw file",
        "",
        _table(["source", "rows"], [[k, v] for k, v in raw["rows_by_source"].items()] + [["**total**", raw["rows"]]]),
        "",
        "Missing values (after normalization; an empty answer is distinct from a short valid answer):",
        "",
        _table(["field", "rows"], [[k, v] for k, v in raw["missing"].items()]),
        "",
        "Rows whose text changed under normalization (NFC + whitespace only):",
        "",
        _table(["field", "rows"], [[k, v] for k, v in raw["normalization_changes"].items()]),
        "",
        "Exact duplicates in the raw file:",
        "",
        _table(
            ["key", "distinct values repeated", "rows in repeated values", "extra copies"],
            [
                [k, v["distinct_values_repeated"], v["rows_in_repeated_values"], v["extra_copies"]]
                for k, v in raw["exact_duplicates"].items()
            ],
        ),
        "",
        "Lengths in words/characters, non-empty rows:",
        "",
        _table(dist_header, _dist_rows({k: v for k, v in raw["lengths_raw_nonempty"].items() if k.startswith(
            ("question", "answer_words", "answer_chars")) and "by_source" not in k})),
        "",
        "Answer words by source:",
        "",
        _table(dist_header, _dist_rows(raw["lengths_raw_nonempty"]["answer_words_by_source"])),
        "",
        "## 2. Exclusions",
        "",
        f"Reconciliation: {corpus['reconciliation']} (source rows = corpus records + excluded rows).",
        "",
        _table(["reason", "rows"], [[k, v] for k, v in exc["by_reason"].items()] + [["**total**", exc["total"]]]),
        "",
        _table(["reason:detail", "rows"], [[k, v] for k, v in exc["by_detail"].items()]),
        "",
        _table(
            ["reason", "rows by source"],
            [[k, ", ".join(f"{s}: {n}" for s, n in v.items())] for k, v in exc["by_reason_and_source"].items()],
        ),
        "",
        "Per-row details (row index, reason, canonical record for duplicates) are in "
        "`data/manifests/exclusions.jsonl`.",
        "",
        "## 3. Corpus",
        "",
        _table(["source", "records"], [[k, v] for k, v in cor["records_by_source"].items()]
               + [["**total**", cor["records"]]]),
        "",
        f"Distinct topics (focus_area): {cor['distinct_topics']}.",
        "",
        "Quality flags (records may carry several; flags describe text, they never change it):",
        "",
        _table(["flag", "records"], [[k, v] for k, v in cor["quality_flags"].items()]),
        "",
        f"Rule-derived question types (`{meta['question_type_rule_version']}`; not the original MedQuAD qtype):",
        "",
        _table(["question_type", "records"], [[k, v] for k, v in cor["question_types"].items()]),
        "",
        _table(dist_header, _dist_rows(cor["lengths"])),
        "",
        "## 4. Grouping",
        "",
        _table(
            ["quantity", "value"],
            [
                ["boilerplate answers (shared by >= "
                 f"{meta['grouping']['boilerplate_min_topics']} topics)", grp["boilerplate_answers"]],
                ["records with a boilerplate answer", grp["boilerplate_records"]],
                ["duplicate groups", grp["duplicate_groups"]],
                ["duplicate groups with > 1 record", grp["duplicate_groups_multi_record"]],
                ["duplicate groups spanning > 1 topic (near-identical text, different condition)",
                 grp["duplicate_groups_multi_topic"]],
                ["records in those groups", grp["records_in_multi_topic_duplicate_groups"]],
                ["near-duplicate pairs (plain shingles, J >= threshold)", grp["near_dup_pairs_j_ge_threshold"]],
                ["template near-duplicate pairs (topic-masked, J >= threshold)",
                 grp["template_near_dup_pairs_j_ge_threshold"]],
                ["residual template pairs (0.5 <= J < threshold)", grp["residual_template_pairs_j_0_5_to_threshold"]],
                ["split groups", grp["split_groups"]],
            ],
        ),
        "",
        "Union-find edges by type: " + ", ".join(f"{k}={v}" for k, v in grp["edges"].items()) + ".",
        "",
        _table(dist_header, _dist_rows({"split_group_size (records)": grp["split_group_size"]})),
        "",
        "## 5. Splits",
        "",
        _table(
            ["split", "records", "groups"],
            [[s, meta["rows_per_split"][s], meta["groups_per_split"][s]] for s in meta["rows_per_split"]],
        ),
        "",
        _table(
            ["split", "records by source"],
            [[s, ", ".join(f"{k}: {v}" for k, v in d.items())] for s, d in meta["rows_per_split_by_source"].items()],
        ),
        "",
        "## 6. Leakage checks",
        "",
        f"Overall: **{'PASSED' if leak['passed'] else 'FAILED'}** (every blocking check must be 0).",
        "",
        _table(["blocking check", "cross-split count"], [[k, v] for k, v in leak["blocking_checks"].items()]),
        "",
        _table(
            ["diagnostic (not blocking)", "value"],
            [[k, v] for k, v in leak["diagnostics"].items() if not k.endswith("_list")],
        ),
        "",
        "Residual cross-split pairs (by record ID and Jaccard) and bracket-stripped topic merges are listed in "
        "`data/manifests/leakage_report.json`.",
        "",
        "## 7. Limitations",
        "",
        f"- {corpus['grouping_disclosure']}",
        "- Near-duplicate candidates need >= "
        f"{meta['grouping']['min_shared_rare_shingles']} shared rare shingles "
        f"(df <= {meta['grouping']['rare_shingle_max_df']}); answers shorter than "
        f"{meta['grouping']['shingle_size']} words, or overlapping only on common shingles, are matched only exactly.",
        "- Boilerplate answers are allowed in several splits by design; they are flagged `boilerplate_answer`.",
        "- A duplicate group can hold near-identical answers about different conditions (counted above); "
        "collapsing retrieval hits by `duplicate_group_id` alone can therefore hide the condition asked about.",
        "",
    ]
    return "\n".join(parts)
