"""Shared typed contracts. Owner: lead. See docs/architecture/contracts.md."""

from medquad_qa.contracts.answerability import AnswerabilityPair, NegativeType, PredictorOutput
from medquad_qa.contracts.evaluation import CaseType, EvaluationExample, EvaluationTrack, LabelProvenance
from medquad_qa.contracts.interfaces import (
    AnswerabilityPredictor,
    ArtifactUnavailableError,
    BatchGenerator,
    ChatMessage,
    ComponentStatus,
    ContractViolationError,
    GenerationError,
    GenerationResult,
    GenerationTimeoutError,
    Generator,
    MedQuADError,
    ModeUnavailableError,
    PipelineObserver,
    QAPipeline,
    ReadinessReporter,
    Retriever,
    RetrieverUnavailableError,
)
from medquad_qa.contracts.qa import (
    EXPERIMENT_MODES,
    FINETUNED_MODES,
    MAX_NEW_TOKENS,
    MAX_QUESTION_CHARS,
    MAX_TOP_K,
    RAG_MODES,
    REQUEST_ID_PATTERN,
    AbstentionReason,
    Citation,
    ExperimentMode,
    GenerationMeta,
    GenerationParams,
    QARequest,
    QAResponse,
    RetrievalHit,
)
from medquad_qa.contracts.records import MedicalRecord, Provenance

CONTRACTS_VERSION = "1.1.1"

__all__ = [
    "CONTRACTS_VERSION",
    "EXPERIMENT_MODES",
    "FINETUNED_MODES",
    "MAX_NEW_TOKENS",
    "MAX_QUESTION_CHARS",
    "MAX_TOP_K",
    "RAG_MODES",
    "REQUEST_ID_PATTERN",
    "AbstentionReason",
    "AnswerabilityPair",
    "AnswerabilityPredictor",
    "ArtifactUnavailableError",
    "BatchGenerator",
    "CaseType",
    "ChatMessage",
    "Citation",
    "ComponentStatus",
    "ContractViolationError",
    "EvaluationExample",
    "EvaluationTrack",
    "ExperimentMode",
    "GenerationError",
    "GenerationMeta",
    "GenerationParams",
    "GenerationResult",
    "GenerationTimeoutError",
    "Generator",
    "LabelProvenance",
    "MedQuADError",
    "MedicalRecord",
    "ModeUnavailableError",
    "NegativeType",
    "PipelineObserver",
    "PredictorOutput",
    "Provenance",
    "QAPipeline",
    "QARequest",
    "QAResponse",
    "ReadinessReporter",
    "RetrievalHit",
    "Retriever",
    "RetrieverUnavailableError",
]
